apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ include "kargo-boilerplate.name" . }}
spec:
  promotionPolicies: {{ toYaml .Values.projectConfig.promotionPolicies | nindent 4 }}
