---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: upgrade-stages-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/34fathombelow/kargo-boilerplate.git
              revision: main
              files:
                - path: "config/apps/*.yaml"
          - clusters:
              selector:
                matchExpressions:
                  - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster,kargo1]}
                matchLabels:
                  stamp: upgrade
  goTemplate: true
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.targetRevision
        - .spec.source.helm.parameters
  template:
    metadata:
      name: '{{ index .metadata.labels "stamp" }}-{{.appName}}-{{ index .metadata.labels "environment" }}'
      annotations:
        kargo.akuity.io/authorized-stage: '{{ index .metadata.labels "stamp" }}-{{.appName}}:{{ index .metadata.labels "environment" }}'
    spec:
      project: kargo-project
      source:
        repoURL: '{{.registry | trimPrefix "oci://" }}'
        chart: '{{ .chartName }}'
        # Kargo will update targetRevision to move new charts into each stage
        targetRevision: 0.1.0 # Initial value needs to exist in remote repo, subsequent revisions will be handled by Kargo.
        helm:
          valueFiles:
            - 'values-{{ index .metadata.labels "environment" }}.yaml' # This is a values file that is _baked into_ the OCI Helm chart.
          parameters:
            # Kargo will update this value to move new images into each stage
            - name: image.tag
              value: 0.1.0
      destination:
        name: '{{.name}}'
        namespace: '{{coalesce .namespace .appName}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
