apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-warehouse
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/34fathombelow/kargo-boilerplate.git
        revision: main
        files:
          - path: "config/apps/*.yaml"
  template:
    metadata:
      name: 'kargo-warehouse-{{.appName}}'
    spec:
      project: kargo-project
      source:
        targetRevision: main
        repoURL: https://github.com/34fathombelow/kargo-boilerplate.git
        path: .
        helm:
          valuesObject:
            nameOverride: '{{.appName}}'
            warehouse:
              subscriptions:
                - chart:
                    repoURL: '{{.registry}}/{{.chart}}'
                - image:
                    repoURL: '{{.image}}'
      destination:
        name: kargo1
      syncPolicy:
        automated: {}
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
